package main

var emojiData = []emoji{
	{"😀", "grinning face", []string{"smile", "happy", "grin"}},
	{"😃", "grinning face with big eyes", []string{"smile", "happy"}},
	{"😄", "grinning face with smiling eyes", []string{"smile", "happy"}},
	{"😁", "beaming face with smiling eyes", []string{"smile", "happy"}},
	{"😆", "grinning squinting face", []string{"laugh", "haha", "funny"}},
	{"😅", "grinning face with sweat", []string{"laugh", "nervous"}},
	{"🤣", "rolling on the floor laughing", []string{"rofl", "lol", "funny", "laughing"}},
	{"😂", "face with tears of joy", []string{"lol", "cry", "laugh", "funny", "laughing"}},
	{"🙂", "slightly smiling face", []string{"smile"}},
	{"🙃", "upside-down face", []string{"silly"}},
	{"😉", "winking face", []string{"wink"}},
	{"😊", "smiling face with smiling eyes", []string{"blush", "happy"}},
	{"😇", "smiling face with halo", []string{"angel", "innocent"}},
	{"🥰", "smiling face with hearts", []string{"love"}},
	{"😍", "smiling face with heart-eyes", []string{"love", "crush", "heart eyes"}},
	{"🤩", "star-struck", []string{"star", "excited", "wow", "amazing"}},
	{"😘", "face blowing a kiss", []string{"kiss", "love"}},
	{"😗", "kissing face", []string{"kiss"}},
	{"😚", "kissing face with closed eyes", []string{"kiss"}},
	{"😋", "face savoring food", []string{"yum", "tasty"}},
	{"😛", "face with tongue", []string{"tongue"}},
	{"😜", "winking face with tongue", []string{"tongue", "silly"}},
	{"🤪", "zany face", []string{"crazy", "silly"}},
	{"🤨", "face with raised eyebrow", []string{"suspicious"}},
	{"🧐", "face with monocle", []string{"thinking", "fancy"}},
	{"🤓", "nerd face", []string{"nerd", "geek"}},
	{"😎", "smiling face with sunglasses", []string{"cool"}},
	{"🥸", "disguised face", []string{"glasses"}},
	{"🤔", "thinking face", []string{"think", "hmm", "wonder", "ponder"}},
	{"🤗", "smiling face with open hands", []string{"hug", "hugging"}},
	{"🤭", "face with hand over mouth", []string{"oops"}},
	{"🤫", "shushing face", []string{"quiet", "shh"}},
	{"🤥", "lying face", []string{"liar", "pinocchio"}},
	{"😶", "face without mouth", []string{"silent"}},
	{"😐", "neutral face", []string{"meh"}},
	{"😑", "expressionless face", []string{"meh"}},
	{"😏", "smirking face", []string{"smirk"}},
	{"😒", "unamused face", []string{"meh", "annoyed"}},
	{"🙄", "face with rolling eyes", []string{"eyeroll"}},
	{"😬", "grimacing face", []string{"awkward"}},
	{"😮‍💨", "face exhaling", []string{"sigh", "phew"}},
	{"🤐", "zipper-mouth face", []string{"quiet", "secret"}},
	{"😪", "sleepy face", []string{"tired"}},
	{"😴", "sleeping face", []string{"sleep", "zzz"}},
	{"😌", "relieved face", []string{"phew"}},
	{"🥱", "yawning face", []string{"tired", "bored"}},
	{"😔", "pensive face", []string{"sad"}},
	{"🤤", "drooling face", []string{"yum"}},
	{"😤", "face with steam from nose", []string{"triumph", "frustrated", "angry"}},
	{"😩", "weary face", []string{"tired", "exhausted"}},
	{"🥹", "face holding back tears", []string{"moved", "touched", "grateful"}},
	{"🫠", "melting face", []string{"melting", "awkward"}},
	{"🫡", "saluting face", []string{"salute", "respect"}},
	{"😷", "face with medical mask", []string{"sick", "mask"}},
	{"🤒", "face with thermometer", []string{"sick", "fever"}},
	{"🤕", "face with head-bandage", []string{"hurt", "injured"}},
	{"🤢", "nauseated face", []string{"sick", "gross"}},
	{"🤮", "face vomiting", []string{"puke", "sick"}},
	{"🤧", "sneezing face", []string{"sick"}},
	{"🥵", "hot face", []string{"sweat", "warm"}},
	{"🥶", "cold face", []string{"freeze"}},
	{"😵", "knocked-out face", []string{"dizzy", "dead"}},
	{"😵‍💫", "face with spiral eyes", []string{"dizzy"}},
	{"🤯", "exploding head", []string{"mind blown", "shock"}},
	{"🤠", "cowboy hat face", []string{"cowboy", "yeehaw"}},
	{"🥳", "partying face", []string{"party", "celebrate"}},
	{"🥺", "pleading face", []string{"please", "begging"}},
	{"😢", "crying face", []string{"sad", "tear"}},
	{"😭", "loudly crying face", []string{"sob", "sad"}},
	{"😡", "pouting face", []string{"angry", "mad"}},
	{"😠", "angry face", []string{"mad"}},
	{"🤬", "face with symbols on mouth", []string{"swear", "curse"}},
	{"😈", "smiling face with horns", []string{"devil", "evil"}},
	{"👿", "angry face with horns", []string{"devil", "imp"}},
	{"💀", "skull", []string{"dead", "lol"}},
	{"☠️", "skull and crossbones", []string{"poison", "death"}},
	{"💩", "pile of poo", []string{"poop", "shit"}},
	{"🤡", "clown face", []string{"clown"}},
	{"👻", "ghost", []string{"spooky", "halloween"}},
	{"👽", "alien", []string{"ufo", "extraterrestrial"}},
	{"👾", "alien monster", []string{"space invader", "game"}},
	{"🤖", "robot", []string{"bot", "ai"}},
	{"😺", "grinning cat", []string{"cat", "smile"}},
	{"😸", "grinning cat with smiling eyes", []string{"cat"}},
	{"😹", "cat with tears of joy", []string{"cat", "lol"}},
	{"😻", "smiling cat with heart-eyes", []string{"cat", "love"}},
	{"😼", "cat with wry smile", []string{"cat", "smirk"}},
	{"😽", "kissing cat", []string{"cat", "kiss"}},
	{"🙀", "weary cat", []string{"cat", "shock"}},
	{"😿", "crying cat", []string{"cat", "sad"}},
	{"😾", "pouting cat", []string{"cat", "angry"}},
	{"👀", "eyes", []string{"look", "watch", "stare", "see"}},
	{"👁️", "eye", []string{"look", "see"}},
	{"🧠", "brain", []string{"smart", "mind", "think"}},
	{"🗣️", "speaking head", []string{"talk", "speak"}},
	{"💬", "speech bubble", []string{"chat", "message", "talk"}},
	{"💭", "thought balloon", []string{"thinking", "idea"}},
	{"🤷", "person shrugging", []string{"shrug", "idk", "whatever"}},
	{"🤦", "person facepalming", []string{"facepalm", "ugh"}},
	{"🏃", "person running", []string{"run", "sprint", "jog"}},
	{"❤️", "red heart", []string{"love", "heart"}},
	{"🧡", "orange heart", []string{"love"}},
	{"💛", "yellow heart", []string{"love"}},
	{"💚", "green heart", []string{"love"}},
	{"💙", "blue heart", []string{"love"}},
	{"💜", "purple heart", []string{"love"}},
	{"🖤", "black heart", []string{"love"}},
	{"🤍", "white heart", []string{"love"}},
	{"🤎", "brown heart", []string{"love"}},
	{"💔", "broken heart", []string{"sad", "heartbreak"}},
	{"❣️", "heart exclamation", []string{"love"}},
	{"💕", "two hearts", []string{"love"}},
	{"💞", "revolving hearts", []string{"love"}},
	{"💓", "beating heart", []string{"love"}},
	{"💗", "growing heart", []string{"love"}},
	{"💖", "sparkling heart", []string{"love"}},
	{"💘", "heart with arrow", []string{"love", "cupid"}},
	{"💝", "heart with ribbon", []string{"love", "gift"}},
	{"💟", "heart decoration", []string{"love"}},
	{"☮️", "peace symbol", []string{"peace"}},
	{"✝️", "latin cross", []string{"christian"}},
	{"☪️", "star and crescent", []string{"islam"}},
	{"🕉️", "om", []string{"hindu"}},
	{"☸️", "wheel of dharma", []string{"buddhist"}},
	{"✡️", "star of david", []string{"jewish"}},
	{"🔯", "dotted six-pointed star", []string{"hexagram"}},
	{"🕎", "menorah", []string{"hanukkah"}},
	{"☯️", "yin yang", []string{"taoism", "balance"}},
	{"☦️", "orthodox cross", []string{"christian"}},
	{"👋", "waving hand", []string{"wave", "hello", "hi", "bye"}},
	{"🤚", "raised back of hand", []string{"hand"}},
	{"🖐️", "hand with fingers splayed", []string{"hand"}},
	{"✋", "raised hand", []string{"high five", "stop"}},
	{"🖖", "vulcan salute", []string{"spock", "star trek"}},
	{"👌", "ok hand", []string{"okay", "perfect"}},
	{"🤌", "pinched fingers", []string{"italian"}},
	{"🤏", "pinching hand", []string{"small", "tiny"}},
	{"✌️", "victory hand", []string{"peace"}},
	{"🤞", "crossed fingers", []string{"luck", "hopeful"}},
	{"🤟", "love-you gesture", []string{"ily", "love"}},
	{"🤘", "sign of the horns", []string{"rock", "metal"}},
	{"🤙", "call me hand", []string{"shaka", "call"}},
	{"👈", "backhand index pointing left", []string{"point", "left"}},
	{"👉", "backhand index pointing right", []string{"point", "right"}},
	{"👆", "backhand index pointing up", []string{"point", "up"}},
	{"🖕", "middle finger", []string{"rude", "fuck"}},
	{"👇", "backhand index pointing down", []string{"point", "down"}},
	{"☝️", "index pointing up", []string{"point", "up"}},
	{"👍", "thumbs up", []string{"yes", "good", "approve", "like", "great", "thumbsup"}},
	{"👎", "thumbs down", []string{"no", "bad", "dislike", "thumbsdown"}},
	{"✊", "raised fist", []string{"power", "solidarity"}},
	{"👊", "oncoming fist", []string{"punch", "bump"}},
	{"🤛", "left-facing fist", []string{"punch", "bump"}},
	{"🤜", "right-facing fist", []string{"punch", "bump"}},
	{"👏", "clapping hands", []string{"clap", "applause"}},
	{"🙌", "raising hands", []string{"praise", "celebrate"}},
	{"👐", "open hands", []string{"hug"}},
	{"🤲", "palms up together", []string{"pray", "cupped"}},
	{"🤝", "handshake", []string{"deal", "agreement"}},
	{"🙏", "folded hands", []string{"pray", "thanks", "please"}},
	{"✍️", "writing hand", []string{"write"}},
	{"💅", "nail polish", []string{"manicure"}},
	{"🤳", "selfie", []string{"phone", "camera"}},
	{"💪", "flexed biceps", []string{"strong", "muscle", "flex"}},
	{"🥊", "boxing glove", []string{"fight", "sport", "box"}},
	{"🔥", "fire", []string{"hot", "lit", "flame"}},
	{"✨", "sparkles", []string{"shiny", "magic"}},
	{"⭐", "star", []string{"star", "favorite"}},
	{"🌟", "glowing star", []string{"star"}},
	{"💫", "dizzy", []string{"star"}},
	{"⚡", "high voltage", []string{"lightning", "fast"}},
	{"💥", "collision", []string{"boom", "explosion"}},
	{"☀️", "sun", []string{"sunny"}},
	{"🌙", "crescent moon", []string{"night"}},
	{"🌕", "full moon", []string{"moon", "night"}},
	{"🌈", "rainbow", []string{"pride", "colorful"}},
	{"☁️", "cloud", []string{"weather"}},
	{"⛅", "sun behind cloud", []string{"weather"}},
	{"🌧️", "cloud with rain", []string{"rain"}},
	{"⛈️", "cloud with lightning and rain", []string{"storm"}},
	{"❄️", "snowflake", []string{"snow", "cold"}},
	{"☔", "umbrella with rain drops", []string{"rain"}},
	{"💧", "droplet", []string{"water"}},
	{"🌊", "water wave", []string{"ocean", "wave"}},
	{"🪐", "ringed planet", []string{"planet", "saturn", "space"}},
	{"🎉", "party popper", []string{"party", "celebrate", "congrats", "yay", "hooray"}},
	{"🎊", "confetti ball", []string{"party"}},
	{"🎈", "balloon", []string{"birthday", "party"}},
	{"🎂", "birthday cake", []string{"birthday", "cake"}},
	{"🎁", "wrapped gift", []string{"present", "birthday"}},
	{"🏆", "trophy", []string{"win", "award"}},
	{"🥇", "1st place medal", []string{"gold", "win"}},
	{"🥈", "2nd place medal", []string{"silver"}},
	{"🥉", "3rd place medal", []string{"bronze"}},
	{"⚽", "soccer ball", []string{"football"}},
	{"🏀", "basketball", []string{"sport"}},
	{"🏈", "american football", []string{"sport"}},
	{"⚾", "baseball", []string{"sport"}},
	{"🎾", "tennis", []string{"sport"}},
	{"🎮", "video game", []string{"gaming", "controller"}},
	{"🎲", "game die", []string{"dice", "random"}},
	{"♟️", "chess pawn", []string{"chess"}},
	{"🎯", "bullseye", []string{"target", "dart"}},
	{"🎵", "musical note", []string{"music"}},
	{"🎶", "musical notes", []string{"music"}},
	{"🎤", "microphone", []string{"sing", "mic"}},
	{"🎧", "headphone", []string{"music", "audio"}},
	{"🎸", "guitar", []string{"music", "rock"}},
	{"🎹", "musical keyboard", []string{"piano", "music"}},
	{"🎨", "artist palette", []string{"art", "design", "creative", "paint"}},
	{"🎭", "performing arts", []string{"theater", "drama"}},
	{"🎓", "graduation cap", []string{"school", "degree", "graduate", "education"}},
	{"📱", "mobile phone", []string{"cellphone", "phone", "smartphone"}},
	{"💻", "laptop", []string{"computer"}},
	{"⌨️", "keyboard", []string{"typing"}},
	{"🖥️", "desktop computer", []string{"computer"}},
	{"🖱️", "computer mouse", []string{"mouse"}},
	{"💾", "floppy disk", []string{"save"}},
	{"💿", "optical disk", []string{"cd"}},
	{"📀", "dvd", []string{"disk"}},
	{"📷", "camera", []string{"photo"}},
	{"📸", "camera with flash", []string{"photo"}},
	{"📹", "video camera", []string{"video"}},
	{"🎥", "movie camera", []string{"film"}},
	{"📺", "television", []string{"tv"}},
	{"🔋", "battery", []string{"power"}},
	{"🔌", "electric plug", []string{"power"}},
	{"💡", "light bulb", []string{"idea", "lightbulb"}},
	{"🔦", "flashlight", []string{"torch"}},
	{"🕯️", "candle", []string{"light"}},
	{"🔔", "bell", []string{"notification", "alert", "ring"}},
	{"📦", "package", []string{"box", "delivery", "ship"}},
	{"🗑️", "wastebasket", []string{"trash", "delete", "bin"}},
	{"📚", "books", []string{"read", "library"}},
	{"📖", "open book", []string{"read"}},
	{"📝", "memo", []string{"note", "write"}},
	{"✏️", "pencil", []string{"write"}},
	{"📌", "pushpin", []string{"pin"}},
	{"📍", "round pushpin", []string{"location", "pin"}},
	{"📎", "paperclip", []string{"attach"}},
	{"🔍", "magnifying glass tilted left", []string{"search", "find"}},
	{"🔎", "magnifying glass tilted right", []string{"search"}},
	{"🔒", "locked", []string{"lock", "secure"}},
	{"🔓", "unlocked", []string{"unlock"}},
	{"🔑", "key", []string{"unlock"}},
	{"🔨", "hammer", []string{"tool"}},
	{"🛠️", "hammer and wrench", []string{"tools", "build"}},
	{"⚙️", "gear", []string{"settings", "cog"}},
	{"🧰", "toolbox", []string{"tools"}},
	{"🧲", "magnet", []string{"attract"}},
	{"💰", "money bag", []string{"cash", "rich"}},
	{"💵", "dollar banknote", []string{"money"}},
	{"💳", "credit card", []string{"payment"}},
	{"💎", "gem stone", []string{"diamond"}},
	{"⚖️", "balance scale", []string{"justice", "law"}},
	{"📈", "chart increasing", []string{"growth", "up"}},
	{"📉", "chart decreasing", []string{"down", "loss"}},
	{"📊", "bar chart", []string{"graph"}},
	{"✅", "check mark button", []string{"yes", "done", "check", "tick", "correct", "complete"}},
	{"❌", "cross mark", []string{"no", "wrong", "x", "error", "cancel"}},
	{"❓", "red question mark", []string{"question", "huh"}},
	{"❗", "red exclamation mark", []string{"warning", "important", "exclamation"}},
	{"⚠️", "warning", []string{"caution", "alert", "danger"}},
	{"♾️", "infinity", []string{"forever", "infinite"}},
	{"🔴", "red circle", []string{"red", "dot"}},
	{"🟢", "green circle", []string{"green", "dot", "online"}},
	{"🔵", "blue circle", []string{"blue", "dot"}},
	{"🚀", "rocket", []string{"launch", "ship", "fast", "startup"}},
	{"🛸", "flying saucer", []string{"ufo"}},
	{"🌍", "globe showing europe-africa", []string{"earth", "world"}},
	{"🌎", "globe showing americas", []string{"earth", "world"}},
	{"🌏", "globe showing asia-australia", []string{"earth", "world"}},
	{"🐶", "dog face", []string{"puppy", "dog"}},
	{"🐱", "cat face", []string{"kitty", "cat"}},
	{"🐭", "mouse face", []string{"mouse"}},
	{"🐹", "hamster", []string{"pet"}},
	{"🐰", "rabbit face", []string{"bunny"}},
	{"🦊", "fox", []string{"animal"}},
	{"🐺", "wolf", []string{"animal"}},
	{"🐻", "bear", []string{"animal"}},
	{"🐼", "panda", []string{"animal"}},
	{"🐨", "koala", []string{"animal"}},
	{"🐯", "tiger face", []string{"animal"}},
	{"🦁", "lion", []string{"animal"}},
	{"🐮", "cow face", []string{"animal"}},
	{"🐷", "pig face", []string{"animal"}},
	{"🐘", "elephant", []string{"animal"}},
	{"🦒", "giraffe", []string{"animal"}},
	{"🐸", "frog", []string{"animal"}},
	{"🐵", "monkey face", []string{"animal"}},
	{"🙈", "see-no-evil monkey", []string{"monkey"}},
	{"🙉", "hear-no-evil monkey", []string{"monkey"}},
	{"🙊", "speak-no-evil monkey", []string{"monkey"}},
	{"🐔", "chicken", []string{"animal"}},
	{"🐧", "penguin", []string{"animal"}},
	{"🐦", "bird", []string{"animal"}},
	{"🦅", "eagle", []string{"animal", "bird"}},
	{"🦉", "owl", []string{"animal", "wise"}},
	{"🦄", "unicorn", []string{"magic"}},
	{"🐝", "honeybee", []string{"bee"}},
	{"🦋", "butterfly", []string{"insect"}},
	{"🐢", "turtle", []string{"animal"}},
	{"🐍", "snake", []string{"animal"}},
	{"🦖", "t-rex", []string{"dinosaur"}},
	{"🐳", "spouting whale", []string{"animal", "ocean"}},
	{"🐬", "dolphin", []string{"animal"}},
	{"🐙", "octopus", []string{"animal"}},
	{"🦀", "crab", []string{"animal"}},
	{"🍎", "red apple", []string{"fruit"}},
	{"🍊", "tangerine", []string{"orange"}},
	{"🍋", "lemon", []string{"fruit"}},
	{"🍌", "banana", []string{"fruit"}},
	{"🍉", "watermelon", []string{"fruit"}},
	{"🍇", "grapes", []string{"fruit"}},
	{"🍓", "strawberry", []string{"fruit"}},
	{"🥝", "kiwi fruit", []string{"fruit"}},
	{"🍅", "tomato", []string{"fruit"}},
	{"🥑", "avocado", []string{"fruit"}},
	{"🍔", "hamburger", []string{"food", "burger"}},
	{"🍟", "french fries", []string{"food"}},
	{"🍕", "pizza", []string{"food"}},
	{"🌭", "hot dog", []string{"food"}},
	{"🌮", "taco", []string{"food"}},
	{"🌯", "burrito", []string{"food"}},
	{"🍣", "sushi", []string{"food"}},
	{"🍜", "steaming bowl", []string{"ramen", "noodles"}},
	{"🍳", "cooking", []string{"egg", "breakfast", "fry"}},
	{"🍩", "doughnut", []string{"donut"}},
	{"🍪", "cookie", []string{"food"}},
	{"🍫", "chocolate bar", []string{"candy"}},
	{"🍿", "popcorn", []string{"snack"}},
	{"🍺", "beer mug", []string{"drink", "alcohol"}},
	{"🍻", "clinking beer mugs", []string{"cheers"}},
	{"🥂", "clinking glasses", []string{"cheers", "wine"}},
	{"🍷", "wine glass", []string{"drink"}},
	{"☕", "hot beverage", []string{"coffee", "tea"}},
	{"🧋", "bubble tea", []string{"drink", "boba"}},
	{"🚗", "automobile", []string{"car"}},
	{"🚕", "taxi", []string{"car"}},
	{"🚌", "bus", []string{"transit"}},
	{"🚎", "trolleybus", []string{"transit"}},
	{"🏎️", "racing car", []string{"fast"}},
	{"🚓", "police car", []string{"cop"}},
	{"🚑", "ambulance", []string{"medical"}},
	{"🚒", "fire engine", []string{"fire truck"}},
	{"✈️", "airplane", []string{"flight", "travel", "plane", "fly"}},
	{"🚂", "locomotive", []string{"train"}},
	{"🚆", "train", []string{"transit"}},
	{"🚲", "bicycle", []string{"bike"}},
	{"🏠", "house", []string{"home"}},
	{"🏢", "office building", []string{"work"}},
	{"🏥", "hospital", []string{"medical"}},
	{"🏫", "school", []string{"education"}},
	{"🏪", "convenience store", []string{"shop"}},
	{"🌳", "deciduous tree", []string{"tree", "nature"}},
	{"🌴", "palm tree", []string{"tropical"}},
	{"🌵", "cactus", []string{"desert"}},
	{"🌲", "evergreen tree", []string{"tree", "pine"}},
	{"🌷", "tulip", []string{"flower"}},
	{"🌹", "rose", []string{"flower"}},
	{"🌻", "sunflower", []string{"flower"}},
	{"🌼", "blossom", []string{"flower"}},
	{"🌸", "cherry blossom", []string{"flower", "sakura"}},
	{"🍀", "four leaf clover", []string{"luck"}},
	{"🍁", "maple leaf", []string{"canada", "autumn"}},
}
